version: '3'
services:
  frontend:
    container_name: portal-iprev
    image: southamerica-east1-docker.pkg.dev/tenacious-text-301013/iprev/frontend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=http,https"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
networks:
  proxy:
    external: true
    name: proxy